# Generated by Django 3.2.9 on 2021-11-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Answers to FAQs',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='uploads/client_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('snipet', models.ImageField(upload_to='uploads/patnership_snipets/')),
            ],
            options={
                'verbose_name_plural': 'MSS Partnerships',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('icon', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'MSS Services',
            },
        ),
        migrations.CreateModel(
            name='Social_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(default='facebook.com', max_length=255)),
                ('tweeter', models.URLField(default='tweeter.com', max_length=255)),
                ('linkedin', models.URLField(default='linkedin.com', max_length=255)),
                ('instagram', models.URLField(default='instagram.com', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('facebook', models.URLField(max_length=255)),
                ('tweeter', models.URLField(max_length=255)),
                ('linkedin', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weighbridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(max_length=255)),
                ('how_it_works', models.TextField(max_length=500)),
                ('summery', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'MSS WeighBridge Services',
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TimeField(max_length=255)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterspace.answers')),
            ],
            options={
                'verbose_name_plural': 'FAQs & QAs',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('vission', models.TextField(max_length=255)),
                ('mission', models.TextField(max_length=255)),
                ('objectives', models.TextField(help_text='MSS Core values', max_length=255)),
                ('email', models.EmailField(default='info@masterspace.co.ke', max_length=254)),
                ('phone', models.CharField(default='+254(0) 773 499 346', help_text='+254{0} xxx xxx xxx', max_length=15)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterspace.location')),
                ('social_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterspace.social_links')),
            ],
            options={
                'verbose_name_plural': 'About MSS & Contacts',
            },
        ),
    ]
