# Generated by Django 3.2.9 on 2021-12-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalues',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/corevalues/'),
        ),
    ]
