# Generated by Django 3.2.7 on 2021-11-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Core Values',
            },
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='objectives',
        ),
        migrations.AddField(
            model_name='social_links',
            name='icon',
            field=models.CharField(blank=True, help_text='use font awesome icons e.g fas fa-tweeter or fa fa-facebook', max_length=50, null=True),
        ),
    ]
