# Generated by Django 3.2.9 on 2021-11-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_links',
            old_name='facebook',
            new_name='_url',
        ),
        migrations.RemoveField(
            model_name='social_links',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='social_links',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='social_links',
            name='tweeter',
        ),
    ]
