# Generated by Django 3.2.9 on 2021-11-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0002_auto_20211106_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='social_links',
        ),
        migrations.AddField(
            model_name='about',
            name='social_links',
            field=models.ManyToManyField(to='masterspace.Social_links'),
        ),
    ]
