# Generated by Django 3.2.7 on 2021-11-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0002_auto_20211127_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corevalues',
            name='text',
        ),
        migrations.AddField(
            model_name='corevalues',
            name='content',
            field=models.CharField(default='content', max_length=255),
        ),
        migrations.AddField(
            model_name='corevalues',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corevalues',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=255),
        ),
    ]
