# Generated by Django 3.2.9 on 2021-12-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0003_auto_20211201_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_classification',
            name='overview',
            field=models.TextField(default='classicficatio description', max_length=500),
        ),
        migrations.AlterField(
            model_name='services',
            name='overview',
            field=models.TextField(default='Service short description here...', max_length=1500),
        ),
    ]
