# Generated by Django 3.2.9 on 2021-11-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0003_auto_20211106_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Our Location'},
        ),
        migrations.AlterModelOptions(
            name='social_links',
            options={'verbose_name_plural': 'Social Media Links'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='about',
            name='overview',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='weighbridge',
            name='how_it_works',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='weighbridge',
            name='introduction',
            field=models.TextField(max_length=500),
        ),
    ]
