# Generated by Django 3.2.7 on 2021-11-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0003_auto_20211127_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_classification',
            name='overview',
            field=models.TextField(default='classicficatio description', max_length=500),
        ),
    ]
