# Generated by Django 3.2.7 on 2021-11-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0004_service_classification_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalues',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
