# Generated by Django 3.2.9 on 2021-11-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0004_auto_20211106_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/teams/'),
        ),
    ]
