# Generated by Django 3.2.9 on 2021-11-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0005_team_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'Organisations & Clients'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Teams & People'},
        ),
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.TextField(max_length=255),
        ),
    ]
