# Generated by Django 3.2.9 on 2021-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0006_auto_20211106_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='answers',
        ),
        migrations.AddField(
            model_name='faqs',
            name='answers',
            field=models.ManyToManyField(to='masterspace.Answers'),
        ),
    ]
