# Generated by Django 3.2.9 on 2021-11-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0008_auto_20211106_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighbridge',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/wb_imgs/'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='snipet',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/patnership_snipets/'),
        ),
    ]
