# Generated by Django 3.2.9 on 2021-11-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0009_auto_20211106_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='date_founded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
