# Generated by Django 3.2.5 on 2021-11-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0010_about_date_founded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_links',
            old_name='_url',
            new_name='link_url',
        ),
    ]
