# Generated by Django 3.2.5 on 2021-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0011_rename__url_social_links_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.CharField(help_text='e.g 3rd,4th,2nd', max_length=4),
        ),
    ]
