# Generated by Django 3.2.5 on 2021-11-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0012_alter_location_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bod_status',
            field=models.BooleanField(default=False),
        ),
    ]
