# Generated by Django 3.2.9 on 2021-11-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0014_auto_20211107_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cms',
            options={'verbose_name_plural': 'Front CMS'},
        ),
        migrations.AddField(
            model_name='cms',
            name='overview',
            field=models.CharField(blank=True, default='Project management', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cms',
            name='short_description',
            field=models.TextField(blank=True, default='We offer quality project management startegies.We have the best project managers the world would ever know!', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cms',
            name='title',
            field=models.CharField(default='We are creative', max_length=100),
        ),
    ]
