# Generated by Django 3.2.9 on 2021-11-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0015_auto_20211107_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='answers',
        ),
        migrations.AddField(
            model_name='faqs',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterspace.answers'),
        ),
    ]
