# Generated by Django 3.2.9 on 2021-11-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0016_auto_20211107_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='answers',
        ),
        migrations.AddField(
            model_name='faqs',
            name='answers',
            field=models.ManyToManyField(to='masterspace.Answers'),
        ),
    ]
