# Generated by Django 3.2.9 on 2021-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0017_auto_20211107_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(max_length=100)),
                ('module_subtitle', models.CharField(max_length=255)),
                ('module_content', models.TextField(max_length=1500)),
            ],
            options={
                'verbose_name_plural': 'Service Modules',
            },
        ),
        migrations.RemoveField(
            model_name='services',
            name='overview',
        ),
        migrations.AddField(
            model_name='services',
            name='Service_modules',
            field=models.ManyToManyField(to='masterspace.Service_modules'),
        ),
    ]
