# Generated by Django 3.2.9 on 2021-11-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0018_auto_20211107_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.DeleteModel(
            name='Weighbridge',
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name_plural': 'MSS WeighBridge Services'},
        ),
        migrations.AlterField(
            model_name='service_modules',
            name='module_content',
            field=models.TextField(default='module #2 content', max_length=1500),
        ),
        migrations.AlterField(
            model_name='service_modules',
            name='module_subtitle',
            field=models.CharField(default='module #2 subtile', max_length=255),
        ),
        migrations.AlterField(
            model_name='service_modules',
            name='module_title',
            field=models.CharField(default='module #2', max_length=100),
        ),
    ]
