# Generated by Django 3.2.9 on 2021-11-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0019_auto_20211107_2359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CMS',
        ),
        migrations.AddField(
            model_name='services',
            name='overview',
            field=models.TextField(default='Service short description here...', max_length=255),
        ),
    ]
