# Generated by Django 3.2.9 on 2021-11-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0020_auto_20211108_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Service_modules',
            field=models.ManyToManyField(blank=True, null=True, to='masterspace.Service_modules'),
        ),
    ]
