# Generated by Django 3.2.9 on 2021-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0021_alter_services_service_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.CharField(help_text='e.g 3rd,4th,2nd', max_length=15),
        ),
    ]
