# Generated by Django 3.2.9 on 2021-11-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0022_alter_location_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='careers_url',
            field=models.URLField(default='https://careers.masterspace.co.ke/', max_length=255),
        ),
    ]
