# Generated by Django 3.2.9 on 2021-11-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0023_about_careers_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='website',
            field=models.URLField(default='example.com', max_length=500),
        ),
    ]
