# Generated by Django 3.2.9 on 2021-11-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterspace', '0025_team_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='thumbnail',
        ),
    ]
